package com.connor.Listing;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

/***
 * @author Connor Hunter
 *
 * Where SQL Queries are written and generated by JpaRepository for accessing Listing information.
 */
@Repository
public interface ListingRepository extends JpaRepository<ListingModel, Long> {

    @Query("SELECT l FROM ListingModel l WHERE l.user.username = :username")
    List<ListingModel> findAllByUsername(@Param("username") String username);
}